#!/bin/bash

read -p "Créer le fichier de suivi commitInfo.txt ? (y/[n]) " yn < /dev/tty
yn=${yn:-n}

case "$yn" in
  [Yy]* )
    mkdir -p suivi
    echo "commit vérifié le $(date '+%Y-%m-%d %H:%M:%S')" > suivi/commitInfo.txt
    git add suivi/commitInfo.txt
    exit 0
    ;;
  * )
    exit 0
    ;;
esac
